### ISSUE TITLE
error building turtlesim

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [ros/ros-overlay#101]
```
[ 92%] Linking CXX executable devel/lib/turtlesim/turtlesim_node
/usr/bin/cmake -E cmake_link_script CMakeFiles/turtlesim_node.dir/link.txt --verbose=1
/usr/bin/g++   -Os -pipe -march=native -mtune=native -fomit-frame-pointer -mfpmath=sse -Wformat -Wformat-security -Wl,-O1 -Wl,--as-needed -Wl,-O2 -Wl,-fuse-ld=gold -Wl,-z,now -Wl,-z,relro -lpthread -lgomp -fweb -fgcse-after-reload -fivopts -fopenmp -Wno-error=implicit-function-declaration -pthread -std=c++11  -Wl,-O1 -Wl,--as-needed -Wl,-O2 -Wl,--as-needed -Wl,-fuse-ld=gold -Wl,-z,now -Wl,-z,relro -lpthread -lgomp CMakeFiles/turtlesim_node.dir/src/turtlesim.cpp.o CMakeFiles/turtlesim_node.dir/src/turtle.cpp.o CMakeFiles/turtlesim_node.dir/src/turtle_frame.cpp.o CMakeFiles/turtlesim_node.dir/include/turtlesim/moc_turtle_frame.cpp.o  -o devel/lib/turtlesim/turtlesim_node  -L/opt/ros/lunar/lib -Wl,-rpath,/opt/ros/lunar/lib: -rdynamic /usr/lib64/libQt5Widgets.so.5.6.2 /opt/ros/lunar/lib/libroscpp.so -lboost_signals-mt /opt/ros/lunar/lib/librosconsole.so /opt/ros/lunar/lib/librosconsole_log4cxx.so /opt/ros/lunar/lib/librosconsole_backend_interface.so -llog4cxx -lboost_regex-mt /opt/ros/lunar/lib/libxmlrpcpp.so /opt/ros/lunar/lib/libroslib.so /opt/ros/lunar/lib/librospack.so -lpython3.5m -lboost_filesystem-mt -lboost_program_options-mt -ltinyxml2 /opt/ros/lunar/lib/libroscpp_serialization.so /opt/ros/lunar/lib/librostime.so /opt/ros/lunar/lib/libcpp_common.so -lboost_system-mt -lboost_thread-mt -lboost_chrono-mt -lboost_date_time-mt -lboost_atomic-mt -lconsole_bridge -lboost_thread-mt -lboost_chrono-mt -lboost_system-mt -lboost_date_time-mt -lboost_atomic-mt /usr/lib64/libQt5Gui.so.5.6.2 /usr/lib64/libQt5Core.so.5.6.2 -lconsole_bridge
make[2]: Leaving directory '/var/tmp/portage/ros-lunar/turtlesim-0.8.0/work/turtlesim-0.8.0_build'
[ 92%] Built target turtlesim_node
Traceback (most recent call last):
  File "/opt/ros/lunar/lib64/python3.5/site-packages/geneus/geneus_main.py", line 137, in genmain
    pkg_map = get_pkg_map()
  File "/opt/ros/lunar/lib64/python3.5/site-packages/geneus/geneus_main.py", line 56, in get_pkg_map
    pkgs = packages.find_packages(ws)
  File "/usr/lib64/python3.5/site-packages/catkin_pkg/packages.py", line 89, in find_packages
    packages = find_packages_allowing_duplicates(basepath, exclude_paths=exclude_paths, exclude_subspaces=exclude_subspaces, warnings=warnings)
  File "/usr/lib64/python3.5/site-packages/catkin_pkg/packages.py", line 128, in find_packages_allowing_duplicates
    xmls[path] = _get_package_xml(os.path.join(basepath, path))
  File "/usr/lib64/python3.5/site-packages/catkin_pkg/package.py", line 391, in _get_package_xml
    raise IOError('Path "%s" is neither a directory containing a "%s" file nor a file' % (path, PACKAGE_MANIFEST_FILENAME))
OSError: Path "/usr/tmp/portage/ros-lunar/camera_calibration_parsers-1.11.12/work/camera_calibration_parsers-1.11.12" is neither a directory containing a "package.xml"
file nor a file
ERROR:  Path "/usr/tmp/portage/ros-lunar/camera_calibration_parsers-1.11.12/work/camera_calibration_parsers-1.11.12" is neither a directory containing a "package.xml" file nor a file
make[2]: *** [CMakeFiles/turtlesim_generate_messages_eus.dir/build.make:103: devel/share/roseus/ros/turtlesim/manifest.l] Error 3
make[2]: Leaving directory '/var/tmp/portage/ros-lunar/turtlesim-0.8.0/work/turtlesim-0.8.0_build'
make[1]: *** [CMakeFiles/Makefile2:997: CMakeFiles/turtlesim_generate_messages_eus.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/portage/ros-lunar/turtlesim-0.8.0/work/turtlesim-0.8.0_build'
make: *** [Makefile:128: all] Error 2
 * ERROR: ros-lunar/turtlesim-0.8.0::ros-overlay failed (compile phase):
 *   emake failed
```

**Comment by Alessandro-Barbieri** [comment]
same with `ros-lunar/pcl_msgs-0.2.0`

**Comment by allenh1** [comment]
That looks like you have a mix of the new install and the old install method going on... You shouldn't have. `dev-python/` anything at this point, just `ros-lunar/*`.

I'm getting ready to clean up the repo, but I've been busy with turtlebot3 and ROS2 lately. I think I will have time for it later this week

**Comment by Alessandro-Barbieri** [comment]
I removed the `dev-python/*::ros-overlay` packages and now it can't find `catkin_pkg`

```
-- Found PythonInterp: /usr/bin/ros-python-lunar (found version "3.5.3")
-- Using PYTHON_EXECUTABLE: /usr/bin/ros-python-lunar
-- Using default Python package layout
-- Found PY_em: /usr/lib64/python3.5/site-packages/em.py
-- Using empy: /usr/lib64/python3.5/site-packages/em.py
-- Using CATKIN_ENABLE_TESTING: ON
-- Skip enable_testing() when building binary package
-- Using CATKIN_TEST_RESULTS_DIR: /var/tmp/portage/ros-lunar/turtlesim-0.8.0/work/turtlesim-0.8.0_build/test_results
-- Found gtest: gtests will be built
-- Using Python nosetests: /usr/bin/nosetests
ImportError: "from catkin_pkg.package import parse_package" failed: No module named 'catkin_pkg'
Make sure that you have installed "catkin_pkg", it is up to date and on the PYTHONPATH.
CMake Error at /opt/ros/lunar/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/usr/bin/ros-python-lunar
  "/opt/ros/lunar/share/catkin/cmake/parse_package_xml.py"
  "/opt/ros/lunar/share/catkin/cmake/../package.xml"
  "/var/tmp/portage/ros-lunar/turtlesim-0.8.0/work/turtlesim-0.8.0_build/catkin/catkin_generated/version/package.cmake")
  returned error code 1
Call Stack (most recent call first):
  /opt/ros/lunar/share/catkin/cmake/catkin_package_xml.cmake:63 (safe_execute_process)
  /opt/ros/lunar/share/catkin/cmake/all.cmake:151 (_catkin_package_xml)
  /opt/ros/lunar/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
See also "/var/tmp/portage/ros-lunar/turtlesim-0.8.0/work/turtlesim-0.8.0_build/CMakeFiles/CMakeOutput.log".
 * ERROR: ros-lunar/turtlesim-0.8.0::ros-overlay failed (configure phase):
 *   cmake failed
```

**Comment by allenh1** [comment]
You'll need to rebuild catkin, I think.

**Comment by allenh1** [comment]
@Alessandro-Barbieri Is this still an issue for you?

**Comment by Alessandro-Barbieri** [comment]
If you want to close it, close it. I'm installing the source based for now and I can't test other methods.

**Comment by allenh1** [comment]
Ok, cool. Just trying to figure out where things are here now that I have some time. Thanks!
