### ISSUE TITLE
ros-lunar/std_msgs (and others): ImportError: No module named deps

### ISSUE THREAD

**Issue by gemarcano** [ros/ros-overlay#230]
I'm not 100% sure what changed in the past 2 days, but as of today, when trying to compile packages (I decided to blow everything out and re-compile everything just to make sure I'm not screwing anything up with my patching), I'm getting that python error during the cmake configuration part. I can provide more logs if necessary, but the relevant output I'm inlining here:
```
/opt/ros/lunar/share/genmsg/cmake/pkg-genmsg.cmake.em:56: error: <type 'exceptions.ImportError'>: No module named deps
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/em.py", line 3302, in <module>
    if __name__ == '__main__': main()
  File "/usr/lib64/python2.7/site-packages/em.py", line 3300, in main
    invoke(sys.argv[1:])
  File "/usr/lib64/python2.7/site-packages/em.py", line 3283, in invoke
    interpreter.wrap(interpreter.file, (file, name))
  File "/usr/lib64/python2.7/site-packages/em.py", line 2295, in wrap
    self.fail(e)
  File "/usr/lib64/python2.7/site-packages/em.py", line 2284, in wrap
    callable(*args)
  File "/usr/lib64/python2.7/site-packages/em.py", line 2359, in file
    self.safe(scanner, done, locals)
  File "/usr/lib64/python2.7/site-packages/em.py", line 2401, in safe
    self.parse(scanner, locals)
  File "/usr/lib64/python2.7/site-packages/em.py", line 2421, in parse
    token.run(self, locals)
  File "/usr/lib64/python2.7/site-packages/em.py", line 1425, in run
    interpreter.execute(self.code, locals)
  File "/usr/lib64/python2.7/site-packages/em.py", line 2595, in execute
    _exec(statements, self.globals, locals)
  File "/usr/lib64/python2.7/site-packages/em.py", line 42, in _exec
    exec("""exec code in globals""")
  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
ImportError: No module named deps
CMake Error at /opt/ros/lunar/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  
  execute_process(/var/tmp/portage/ros-lunar/std_msgs-0.5.11/work/std_msgs-0.5.11_build/catkin_generated/env_cached.sh
  "/usr/bin/python" "/usr/lib64/python2.7/site-packages/em.pyc"
  "--raw-errors" "-F"
  "/var/tmp/portage/ros-lunar/std_msgs-0.5.11/work/std_msgs-0.5.11_build/cmake/std_msgs-genmsg-context.py"
  "-o"
  "/var/tmp/portage/ros-lunar/std_msgs-0.5.11/work/std_msgs-0.5.11_build/cmake/std_msgs-genmsg.cmake"
  "/opt/ros/lunar/share/genmsg/cmake/pkg-genmsg.cmake.em") returned error
  code 1
Call Stack (most recent call first):
  /opt/ros/lunar/share/catkin/cmake/em_expand.cmake:25 (safe_execute_process)
  /opt/ros/lunar/share/genmsg/cmake/genmsg-extras.cmake:303 (em_expand)
  CMakeLists.txt:43 (generate_messages)


-- Configuring incomplete, errors occurred!
```

**Comment by gemarcano** [comment]
Well, that's weird. Since `deps` isn't in the portage tree, I made an ebuild for it (so it actually gets installed to system folders properly)... and the error persists. Something else has to be going on...

I'm inlining the ebuild, just in case someone wants to try it. It is super bare-bones, and I was surprised it installed, but I made sure `deps` could be imported from all of my python interpreters (well, it's just 2.7 and 3.4 for now).
```
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

PYTHON_COMPAT=( python2_7 python3_4 )
inherit distutils-r1

DESCRIPTION=""
HOMEPAGE="https://github.com/dejw/deps/"
SRC_URI="https://pypi.python.org/packages/49/0e/50c8ea5290e4bbb1ac51b560a01daabe5caa14968c167d57ef1e2a8c39cb/deps-0.1.0.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

DEPEND=""
RDEPEND="${DEPEND}"
```

**Comment by gemarcano** [comment]
Alright, now I'm getting somewhere. The actual module missing is `genmsg.deps`. Trying to track down what's going on... since `genmsg` is installed on my system (maybe it got corrupted???).

**Comment by gemarcano** [comment]
Seems like I had some weirdly stale genmsg files in `/usr/lib64/python*/site-packages/` (I'm not even sure how they ended up there, since they didn't belong to any package and pip wasn't tracking them). Now that I've nuked those rogue files, compilation is happening as intended. Looks like this was an environmental issue on my end and not a bug in the repository. Closing...
