### ISSUE TITLE
rosbag call for a python3 pickle

### ISSUE THREAD

**Issue by MalcolmMielle** [ros/ros-overlay#295]
Hej hej,

So invoking rosbag check uses a pickle protocol that does not work with python2 apparently. For now my ros install is entirely restricted to python2.7, but maybe this package shouldn't. So I'm leaving this here in case it's useful to know as a "bug" although it doesn't really feel like one :)

```
$ rosbag check slam_dortmund_acg_laser.bag 
Traceback (most recent call last):
  File "/opt/ros/lunar/bin/rosbag", line 35, in <module>
    rosbag.rosbagmain()
  File "/opt/ros/lunar/lib64/python2.7/site-packages/rosbag/rosbag_main.py", line 896, in rosbagmain
    cmds[cmd](argv[2:])
  File "/opt/ros/lunar/lib64/python2.7/site-packages/rosbag/rosbag_main.py", line 483, in check_cmd
    mm = MessageMigrator(args[1:] + append_rule, not options.noplugins)
  File "/opt/ros/lunar/lib64/python2.7/site-packages/rosbag/migration.py", line 529, in __init__
    for pkg in rospack.get_depends_on(dep, implicit=False):
  File "/usr/lib64/python2.7/site-packages/rospkg/rospack.py", line 268, in get_depends_on
    m = self.get_manifest(r)
  File "/usr/lib64/python2.7/site-packages/rospkg/rospack.py", line 167, in get_manifest
    return self._load_manifest(name)
  File "/usr/lib64/python2.7/site-packages/rospkg/rospack.py", line 211, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name, rospack=self)
  File "/usr/lib64/python2.7/site-packages/rospkg/manifest.py", line 412, in parse_manifest_file
    _static_rosdep_view = init_rospack_interface()
  File "/usr/lib64/python2.7/site-packages/rosdep2/rospack.py", line 58, in init_rospack_interface
    lookup = _get_default_RosdepLookup(Options())
  File "/usr/lib64/python2.7/site-packages/rosdep2/main.py", line 128, in _get_default_RosdepLookup
    verbose=options.verbose)
  File "/usr/lib64/python2.7/site-packages/rosdep2/sources_list.py", line 613, in create_default
    sources = load_cached_sources_list(sources_cache_dir=sources_cache_dir, verbose=verbose)
  File "/usr/lib64/python2.7/site-packages/rosdep2/sources_list.py", line 514, in load_cached_sources_list
    return parse_sources_data(cache_data, origin=cache_index, model=model)
  File "/usr/lib64/python2.7/site-packages/rosdep2/sources_list.py", line 372, in parse_sources_data
    raise InvalidData("line:\n\t%s\n%s"%(line, e), origin=origin)
rosdep2.core.InvalidData: line:
	yaml https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml osx
unsupported pickle protocol: 4
```

See [here](https://stackoverflow.com/questions/41920398/valueerror-unsupported-pickle-protocol-4-with-pandas) for more detail on the error.

**Comment by MalcolmMielle** [comment]
Ups easy solution is to not frget to build rosdep with python2.7 only too:

```
dev-python/rosdep PYTHON_TARGETS: -* python2_7
dev-python/rosdep PYTHON_SINGLE_TARGET: -* python2_7
```

**Comment by allenh1** [comment]
@MalcolmMielle Ya, that's one solution. Another fix is to just clean up the `~/.ros/rosdep` folder.

This was discussed [here](https://github.com/ros-infrastructure/rosdep/issues/457) in the past.

**Comment by im-Kitsch** [comment]
@allenh1  But if I  clean up rosdep folder, I still nedd to do $rosdep update, then the probelm comes again.

**Comment by allenh1** [comment]
> @allenh1 But if I clean up rosdep folder, I still nedd to do $rosdep update, then the probelm comes again.

If you clean the rosdep folder and do a `rosdep update` with the python version you will be using, then a should be fine.

With ROS 1 I still strongly recommend only doing Python 2, since much of ROS 1 has not yet been moved to Python 3, and, although it may install, it likely won't function (one such important package is `tf` -- though `tf` has been deprecated for several years now).
