### ISSUE TITLE
dev-python/superflore Fails to emerge

### ISSUE THREAD

**Issue by allenh1** [ros/ros-overlay#501]
I'm adding an ebuild for [`superflore`](https://github.com/ros-infrastructure/superflore), but it's not quite working. I'll update the progress on this issue for visibility. Also, until ros-infrastructure/superflore#139 is merged, you'll need to add that patch.

```
mkdir -p /etc/portage/patches/dev-python/superflore-9999
wget -O /etc/portage/patches/dev-python/superflore-9999/fix-install.patch https://patch-diff.githubusercontent.com/raw/ros-infrastructure/superflore/pull/139.patch
```

**Comment by allenh1** [comment]
Current backtrace:

``` # superflore-gen-ebuilds 
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.5/superflore-gen-ebuilds", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 3161, in <module>
    @_call_aside
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 3145, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 3174, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'argparse' distribution was not found and is required by rosinstall-generator
```

**Comment by allenh1** [comment]
To fix the above, you need to install pip.

```
emerge dev-python/pip
pip install --user argparse
```

So it looks like this is a `rosintall-generator` issue, as opposed to a `superflore` issue.

**Comment by allenh1** [comment]
Looks like you can see the issue here.

https://github.com/ros-infrastructure/rosinstall_generator/blob/ce4e6ec834d1c7238ebfaf7243d355bde3b5676e/setup.py#L11

**Comment by allenh1** [comment]
The above PR has been integrated into the overlay (as of df1379f8af541b23ea117d47b51ef0a9a5d5d0b3).

After the user patch is applied, things seem to be functional.

**Comment by allenh1** [comment]
Everything is now merged, so this is no longer an issue. :tada:.
