### ISSUE TITLE
Python version (I think) problems

### ISSUE THREAD

**Issue by flabrosse** [ros/ros-overlay#736]
We have ROS running on several of our computers and robots.  Two of the robots have lunar on.  Following an update, one of them refuses to work (for example, I can't run roscore).  The initial problem was a syntax error in yaml, indicating that the wrong python interpreter was used with the wrong files, according to google.

I compared the non-working install with the working install and noticed that some of the non-essential packages (not needed to run roscore) on the working install are older, but the essential stuff is at the same version on both computers, and both use the same set of python interpreters.  But no joy.

I removed the whole of ROS including dependencies from the non working install and reinstalled with the same settings as with the working install.  Still no joy!

I reinstalled the whole of it with only python2_7.  I can now run roscore!  But catkin make complains that  argparse is not found.  The interesting bit is that it is setuptools that complains, running python3_5!  and argparse is in all versions of python (2_7, 3_5 and 3_6) installed on that computer.

I'm running out of ideas.  It seems that the whole thing is a bit fragile when it comes to multiple slotted python versions, but I don't think I can only have python2_7 on gentoo any more.

Any suggestions?

**Comment by awesomebytes** [comment]
I have not managed to have ROS deal in a friendly manner with Python > 2.7, but I do have python 2.7 and 3.6 living together.

This is what I do (taken from @allenh1 Docker files):
```bash
echo "# From the Docker image of ros-overlay\n\
# mainly force to build just Python 2.7\n\
ros-indigo/* PYTHON_TARGETS: -* python2_7\n\
ros-indigo/* PYTHON_SINGLE_TARGET: -* python2_7\n\
ros-kinetic/* PYTHON_TARGETS: -* python2_7\n\
ros-kinetic/* PYTHON_SINGLE_TARGET: -* python2_7\n\
ros-lunar/* PYTHON_TARGETS: -* python2_7\n\
ros-lunar/* PYTHON_SINGLE_TARGET: -* python2_7\n\
" >> $EPREFIX/etc/portage/package.use
```
The argparse thing is cause you are trying to run catkin_make or similar with python3 and it is not supported as far as I know.

**Comment by flabrosse** [comment]
I have something very similar to that, also coming from the same source ;-).  I have also added ros specific python packages with the same constraint.

Yes, I do agree that the argparse problem is from running catkin with 3.5, but I am not.  Catkin is running with 2.7 and despite having selected to use python 2.7 (and 3.5 and 3.6 as fallback) it seems to be looking for argparse with 3.5.  The computer is turned off at the moment so I can't send the exact error message right now, but will do so tomorrow.

**Comment by awesomebytes** [comment]
I'd say check your PYTHON_PACKAGE_PATH env car to be sure it's not pointing
to something py3.

Also check the catkin related packages for py3 shebangs.

If nothing interesting comes up, start adding prints on the way to that
catkin_make call (in the script that does catkin_make and follow down the
rabbit hole). I've had some similar issue and it was because of the python
path. Then  because of the shebang. And then because of emerging something
without disabling the py3 target.

Good luck, sorry for typos, writing from my phone.

**Comment by flabrosse** [comment]
@awesomebytes this is a good pointer!  I don't have a PYTHON_PACKAGE_PATH env var, but do have a PYTHONPATH, that contains python3.5 directories.  This is set by _setup_util.py: in my devel directory.  I edited it to replace 3.5 with 2.7 and now PYTHONPATH only contains mentions of 2.7.  So far, seems promising.

However, running catkin_make gives me almost the same error as above, replacing 3_5 with 2_7.  So it is using only python2.7, but failing, still, to find argparse.

**Comment by awesomebytes** [comment]
You installed catkin with Python 3.6 Target still enabled and that  wrote
that setup file and it messed up your PYTHONPATH For any script. I did the
same once.

I'd recommend re-emerging  anything related to catkin, and if you can, ROS.
Making sure there are no py3 targets set for any of them.

If you check the Dockerfiles from my project:

https://github.com/awesomebytes/ros_overlay_on_gentoo_prefix/tree/master/ros_base

First Dockerfile then Dockerfile2, that will emerge a full ros_base of
ros-kinetic successfully. (On Gentoo Prefix). You can find all the commands
I needed to do.

**Comment by flabrosse** [comment]
catkin and catkin_pkg are installed with only 2.7 support:
```
$ eix -I catkin
[I] dev-python/catkin_pkg
     Available versions:  (~)0.4.6[1] ~0.4.7 ~0.4.8 ~0.4.9 **9999 {test PYTHON_TARGETS="pypy pypy3 python2_7 python3_4 python3_5 python3_6"}
     Installed versions:  0.4.6[1](14:47:09 19/12/18)(PYTHON_TARGETS="python2_7 -python3_4 -python3_5")
     Homepage:            http://wiki.ros.org/catkin_pkg
     Description:         Standalone Python library for the catkin package system

[I] ros-lunar/catkin [1]
     Available versions:  (~)0.7.14 {test PYTHON_TARGETS="python2_7 python3_5 python3_6"}
     Installed versions:  0.7.14(14:47:24 19/12/18)(-test PYTHON_TARGETS="python2_7 -python3_5 -python3_6")
     Homepage:            http://www.ros.org/wiki/catkin
     Description:         Low-level build system macros and infrastructure for ROS.

[1] "ros-overlay" /var/lib/layman/ros-overlay

Found 2 matches
```
Installing ros_base is what I did with all ros packages and all python-dev required by ros-lunar packages with only python2.7 allowed:
```
ros-*/* PYTHON_TARGETS: -* python2_7
ros-*/* PYTHON_SINGLE_TARGET: -* python2_7
dev-python/rosdep PYTHON_TARGETS: -* python2_7
dev-python/rospkg PYTHON_TARGETS: -* python2_7
dev-python/rosinstall_generator PYTHON_TARGETS: -* python2_7
dev-python/rosdistro PYTHON_TARGETS: -* python2_7
dev-python/catkin_pkg PYTHON_TARGETS: -* python2_7
dev-python/pyyaml PYTHON_TARGETS: -* python2_7
dev-python/wstool PYTHON_TARGETS: -* python2_7
dev-python/vcstools PYTHON_TARGETS: -* python2_7
```
And the python trace only refers to 2.7 now.  My environment only refers to python2.7 (in PYTHONPATH).

I just created a new catkin_ws, starting from scratch. Same problem.

**Comment by flabrosse** [comment]
BTW, I do appreciate all these suggestions!  Thanks for helping!

**Comment by awesomebytes** [comment]
Oh man, that is hard. I'd grep the hell out of the filesystem for Python3
references.

Try the lib/python2.7 folders, both Gentoo and ROS overlay. Any combination
you can think of python2.7, python2... If it's an option... Even uninstall
python3? (I don't know if that would break your installation).

**Comment by allenh1** [comment]
>  Installed versions: 0.4.6[1](14:47:09 19/12/18)(PYTHON_TARGETS="python2_7 -python3_4 -python3_5")

Re-emerge your `catkin_pkg`. It is out of date. This is because the `setup.py` for `catkin_pkg` lists `argparse` as a module dependency, and you don't have it since it has been a part of the language since Python 2.7.

**Comment by allenh1** [comment]
See ros-infrastructure/catkin_pkg#239

**Comment by flabrosse** [comment]
I'm pretty sure I had the last version of catkin_pkg at some point and went back to that one because the more recent ones are not in the overlay so I thought this could create conflicts.  Unfortunately this will have to wait until next year now.  I'll report back.

**Comment by flabrosse** [comment]
> > Installed versions: 0.4.6[1](14:47:09 19/12/18)(PYTHON_TARGETS="python2_7 -python3_4 -python3_5")
> 
> Re-emerge your `catkin_pkg`. It is out of date. This is because the `setup.py` for `catkin_pkg` lists `argparse` as a module dependency, and you don't have it since it has been a part of the language since Python 2.7.

I tried that:
```
# eix catkin_pkg
[I] dev-python/catkin_pkg
     Available versions:  (~)0.4.6[1] ~0.4.7 ~0.4.8 (~)0.4.9 **9999 {test PYTHON_TARGETS="pypy pypy3 python2_7 python3_4 python3_5 python3_6"}
     Installed versions:  0.4.9(13:52:10 07/01/19)(-test PYTHON_TARGETS="python2_7 -pypy -pypy3 -python3_4 -python3_5 -python3_6")
     Homepage:            http://wiki.ros.org/catkin_pkg
     Description:         Standalone Python library for the catkin package system

[1] "ros-overlay" /var/lib/layman/ros-overlay
```
and get
```
$ catkin_make
Base path: /home/ffl/catkin_ws
Source space: /home/ffl/catkin_ws/src
Build space: /home/ffl/catkin_ws/build
Devel space: /home/ffl/catkin_ws/devel
Install space: /home/ffl/catkin_ws/install
####
#### Running command: "make cmake_check_build_system" in "/home/ffl/catkin_ws/build"
####
CMake Error at CMakeLists.txt:20 (message):
  Search for 'catkin' in workspace failed (catkin_find_pkg catkin
  /home/ffl/catkin_ws/src): Traceback (most recent call last):

    File "/usr/lib/python-exec/python2.7/catkin_find_pkg", line 6, in <module>
      from pkg_resources import load_entry_point
    File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3161, in <module>
      @_call_aside
    File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3145, in _call_aside
      f(*args, **kwargs)
    File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3174, in _initialize_master_working_set
      working_set = WorkingSet._build_master()
    File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_master
      ws.require(__requires__)
    File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 984, in require
      needed = self.resolve(parse_requirements(requirements))
    File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 870, in resolve
      raise DistributionNotFound(req, requirers)

  pkg_resources.DistributionNotFound: The 'argparse' distribution was not
  found and is required by catkin-pkg


-- Configuring incomplete, errors occurred!
See also "/home/ffl/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/ffl/catkin_ws/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:2084: cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed
```
So now all python2.7 being used, and still the problem.

**Comment by flabrosse** [comment]
Solved!  Following thread #99 I looked at the patches each of the packages use.  catkin_pkg-0.4.9 does **not** use the argparse patch.  catkin_pkg-0.4.8 does.  I down-graded to that and it now works.

**Comment by flabrosse** [comment]
And now the only two versions available of catkin_pkg are 0.4.9 and 0.4.10, neither of which uses the argparse patch.  Given how unreliable is the install with anything else than python 2.7, I had to only build for python 2.7, only to now face this problem.
Is there a solution?

**Comment by flabrosse** [comment]
Just for info, catkin_pkg-0.4.12 seems to work.

**Comment by allenh1** [comment]
> Just for info, catkin_pkg-0.4.12 seems to work.

That's great news! I'll update  the core ebuilds later today (I haven't done that in a good while).

**Comment by flabrosse** [comment]
Before you do an update, it might be worth noting that since gentoo changed profiles to 17.1, I have not been able to compile any of the ros packages.  I get:

```No rule to make target '/usr/lib/libpython2.7.so'```

the reason being that libpython2.7.so is now in /usr/lib64.  I haven't yet found a solution to that.

And it's not just python that is looked for in the wrong place.  My own packages fail with boost libs found by cmake in the correct place but linked in the wrong directory.

**Comment by allenh1** [comment]
> Before you do an update, it might be worth noting that since gentoo changed profiles to 17.1, I have not been able to compile any of the ros packages

I'll try changing the docker image to use a newer profile and we'll see what happens then. Thanks for the note.
