### ISSUE TITLE
Cannot create workspace: catkin_make => pkg_resources.DistributionNotFound: The 'argparse' distribution was not   found and is required by catkin-pkg

### ISSUE THREAD

**Issue by archenroot** [ros/ros-overlay#99]
I tried to create my catking workspace:
```
zangetsu@ares ~/catkin_ws $ catkin_make
Base path: /home/zangetsu/catkin_ws
Source space: /home/zangetsu/catkin_ws/src
Build space: /home/zangetsu/catkin_ws/build
Devel space: /home/zangetsu/catkin_ws/devel
Install space: /home/zangetsu/catkin_ws/install
####
#### Running command: "cmake /home/zangetsu/catkin_ws/src -DCATKIN_DEVEL_PREFIX=/home/zangetsu/catkin_ws/devel -DCMAKE_INSTALL_PREFIX=/home/zangetsu/catkin_ws/install -G Unix Makefiles" in "/home/zangetsu/catkin_ws/build"
####
CMake Error at CMakeLists.txt:20 (message):
  Search for 'catkin' in workspace failed (catkin_find_pkg catkin
  /home/zangetsu/catkin_ws/src): Traceback (most recent call last):

    File "/usr/lib/python-exec/python3.5/catkin_find_pkg", line 6, in <module>
      from pkg_resources import load_entry_point
    File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 3036, in <module>
      @_call_aside
    File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
      f(*args, **kwargs)
    File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
      working_set = WorkingSet._build_master()
    File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 654, in _build_master
      ws.require(__requires__)
    File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 968, in require
      needed = self.resolve(parse_requirements(requirements))
    File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 854, in resolve
      raise DistributionNotFound(req, requirers)

  pkg_resources.DistributionNotFound: The 'argparse' distribution was not
  found and is required by catkin-pkg


-- Configuring incomplete, errors occurred!
See also "/home/zangetsu/catkin_ws/build/CMakeFiles/CMakeOutput.log".
Invoking "cmake" failed

```
I tried to test argparse which is now part of Python distribution and it works:
```
ares ros-lunar # python
Python 3.5.3 (default, Jun 11 2017, 18:35:06) 
[GCC 5.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import argparse
>>> parser = argparse.ArgumentParser()
>>> parser.parse_args()
Namespace()

```

Could it be some back in catkin_pkg?

**Comment by allenh1** [comment]
I had to pip install that (for some reason). I think this is similar to empy.

**Comment by archenroot** [comment]
Ok, good to know, so it is broken in the moment, I have on my system following versions available:
```
ares opencv # locate catkin_pkg |grep ebuild
/usr/portage/dev-python/catkin_pkg/catkin_pkg-0.3.4.ebuild
/usr/portage/dev-python/catkin_pkg/catkin_pkg-0.3.5.ebuild
/usr/portage/dev-python/catkin_pkg/catkin_pkg-9999.ebuild
/var/db/pkg/dev-python/catkin_pkg-0.3.4/catkin_pkg-0.3.4.ebuild
/var/repo/ros-overlay/dev-python/catkin_pkg/catkin_pkg-0.3.4.ebuild

```
I have installed following packages:
```
ares opencv # eix --nocolor -c -I -C |grep catkin
[I] dev-python/catkin_pkg (0.3.4[8]@06/11/2017): Standalone Python library for the catkin package system
[I] dev-python/rosdistro (0.6.2@06/11/2017): Tools to work with catkinized rosdistro files
[I] ros-kinetic/catkin [8] (0.7.6@06/11/2017): Low-level build system macros and infrastructure for ROS.
[I] ros-lunar/catkin [8] (0.7.6@06/11/2017): Low-level build system macros and infrastructure for ROS.

```

NOTE: Gentoo in general doesn't provide or it is hard to check which overlay is used for installed package the 0.3.4.0 versions are available in both Gentoo and overlay:
```
ares opencv # equery meta dev-python/catkin_pkg
 * dev-python/catkin_pkg [ros-overlay]
Maintainer:  None specified
Upstream:    None specified
Homepage:    http://wiki.ros.org/catkin_pkg
Location:    /var/repo/ros-overlay/dev-python/catkin_pkg
Keywords:    0.3.4:0: amd64 arm x86 ~arm64
Keywords:    0.3.5:0: ~amd64 ~arm
Keywords:    9999:0: 
License:     BSD-3
```
But in main Gentoo tree the package has **4 patches, one of those is argparse**:
```
PATCHES=(
	"${FILESDIR}/catkin_prefix.patch"
        "${FILESDIR}/argparse.patch"
        "${FILESDIR}/ros_packages.patch"
        "${FILESDIR}/infinite_loop.patch"
)

```

**Comment by archenroot** [comment]
Co I created a new package ebuild in ros-overlay and actually completely copied the ebuild from Gentoo tree ( I wanted to keep it in overlay to prevent some unexpected issues with mixed stuff I experienced previously):
`>>> Installing (1 of 1) dev-python/catkin_pkg-0.3.5::ros-overlay`

Now when I create catkin workspace, it works:
```
zangetsu@ares ~/catkin_ws $ catkin_make
Base path: /home/zangetsu/catkin_ws
Source space: /home/zangetsu/catkin_ws/src
Build space: /home/zangetsu/catkin_ws/build
Devel space: /home/zangetsu/catkin_ws/devel
Install space: /home/zangetsu/catkin_ws/install
Creating symlink "/home/zangetsu/catkin_ws/src/CMakeLists.txt" pointing to "/opt/ros/lunar/share/catkin/cmake/toplevel.cmake"
####
#### Running command: "cmake /home/zangetsu/catkin_ws/src -DCATKIN_DEVEL_PREFIX=/home/zangetsu/catkin_ws/devel -DCMAKE_INSTALL_PREFIX=/home/zangetsu/catkin_ws/install -G Unix Makefiles" in "/home/zangetsu/catkin_ws/build"
####
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/lib/ccache/bin/cc
-- Check for working C compiler: /usr/lib/ccache/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/ccache/bin/c++
-- Check for working CXX compiler: /usr/lib/ccache/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /home/zangetsu/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/lunar
-- This workspace overlays: /opt/ros/lunar
-- Found PythonInterp: /usr/bin/python (found version "3.5.3") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using default Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/zangetsu/catkin_ws/build/test_results
-- Found gtest: gtests will be built
-- Using Python nosetests: /usr/bin/nosetests
-- catkin 0.7.6
-- BUILD_SHARED_LIBS is on
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zangetsu/catkin_ws/build
####
#### Running command: "make -j8 -l8" in "/home/zangetsu/catkin_ws/build"
####

```

I think important than other details are 4 available patches provided by Gentoo ROS.

**Comment by Alessandro-Barbieri** [comment]
I only use the downstream versions, are better maintained.

**Comment by archenroot** [comment]
@Alessandro-Barbieri 
Yes, @allenh1 told me to remove completely dev-python from the ros-overlay folder while resolving other issue before... so we build only on Gentoo dev-python packages.
